/**
 * Generates src/data/edge-functions.generated.ts — a static manifest of all
 * Supabase edge functions in supabase/functions, used by the Admin Portal
 * "Edge Functions" view.
 *
 * Run: bun run scripts/generate-edge-functions-manifest.ts
 */
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs"
import { join } from "node:path"

const FUNCTIONS_DIR = "supabase/functions"
const CONFIG_PATH = "supabase/config.toml"
const OUT_PATH = "src/data/edge-functions.generated.ts"

function parseVerifyJwt(): Record<string, boolean> {
  const config = readFileSync(CONFIG_PATH, "utf8")
  const map: Record<string, boolean> = {}
  const re = /\[functions\.([^\]]+)\]\s*\n(?:[^[]*?)verify_jwt\s*=\s*(true|false)/g
  let m: RegExpExecArray | null
  while ((m = re.exec(config))) map[m[1]] = m[2] === "true"
  return map
}

function describe(source: string): string {
  const lines = source.split("\n")
  const parts: string[] = []
  for (const raw of lines) {
    const line = raw.trim()
    if (!line) {
      if (parts.length) break
      continue
    }
    if (line.startsWith("//")) parts.push(line.replace(/^\/\/\s?/, ""))
    else if (line.startsWith("/*") || line.startsWith("*")) {
      const cleaned = line
        .replace(/^\/\*+\s?/, "")
        .replace(/^\*+\/?\s?/, "")
        .replace(/\*\/$/, "")
        .trim()
      if (cleaned) parts.push(cleaned)
    } else break
  }
  return parts.join(" ").trim().slice(0, 300)
}

const verifyJwt = parseVerifyJwt()

const names = readdirSync(FUNCTIONS_DIR)
  .filter(
    (n) => !n.startsWith("_") && !n.includes(".") && statSync(join(FUNCTIONS_DIR, n)).isDirectory(),
  )
  .sort()

const entries = names.map((name) => {
  const entry = join(FUNCTIONS_DIR, name, "index.ts")
  const source = existsSync(entry) ? readFileSync(entry, "utf8") : ""
  const secrets = Array.from(
    new Set(
      Array.from(source.matchAll(/Deno\.env\.get\(\s*['"]([A-Z0-9_]+)['"]/g)).map((m) => m[1]),
    ),
  ).sort()
  return {
    name,
    description: describe(source),
    verifyJwt: verifyJwt[name] ?? null,
    secrets,
    lines: source ? source.split("\n").length : 0,
  }
})

const banner = `// AUTO-GENERATED by scripts/generate-edge-functions-manifest.ts — do not edit by hand.\n`
const body = `export interface EdgeFunctionInfo {
  name: string;
  description: string;
  /** verify_jwt from supabase/config.toml; null when not configured explicitly. */
  verifyJwt: boolean | null;
  secrets: string[];
  lines: number;
}

export const EDGE_FUNCTIONS: EdgeFunctionInfo[] = ${JSON.stringify(entries, null, 2)};

export const EDGE_FUNCTIONS_GENERATED_AT = ${JSON.stringify(new Date().toISOString())};
`

writeFileSync(OUT_PATH, banner + body)
console.log(`Wrote ${entries.length} functions to ${OUT_PATH}`)
