
INSERT INTO ai_action_flows (organization_id, widget_config_id, intent_key, label, description, trigger_phrases, requires_verification, flow_steps, is_active, sort_order)
VALUES
  ('b9b4df82-2b89-4a64-b2a3-5e19c0e8d43b', '2f1fab67-4177-4a69-870f-e556ca5219bd', 'new_booking', 'Book New Service', 'Customer wants to book a new service', ARRAY['book a service','I want to order','bestille','bestill time','new booking','book appointment'], true, '[{"id":"step_1","type":"collect","field":"address","marker":"ADDRESS_SEARCH","instruction":"Ask for delivery address and validate it is within service area"},{"id":"step_2","type":"collect","field":"license_plate","marker":"LICENSE_PLATE","instruction":"Ask for car registration number to look up vehicle"},{"id":"step_3","type":"collect","field":"service","marker":"SERVICE_SELECT","instruction":"Show available services for the selected address and let customer choose"},{"id":"step_4","type":"collect","field":"time_slot","marker":"TIME_SLOT","instruction":"Show available delivery windows and let customer pick a time"},{"id":"step_5","type":"confirm","field":"summary","marker":"BOOKING_SUMMARY","instruction":"Show booking summary and confirm the order"}]'::jsonb, true, 0),
  ('b9b4df82-2b89-4a64-b2a3-5e19c0e8d43b', '2f1fab67-4177-4a69-870f-e556ca5219bd', 'change_time', 'Change Booking Time', 'Customer wants to reschedule a booking', ARRAY['change time','reschedule','move booking','endre tid','flytte time'], true, '[{"id":"step_1","type":"lookup","field":"booking","marker":"","instruction":"Identify which booking the customer wants to change. Use their verified phone to look up pending bookings."},{"id":"step_2","type":"collect","field":"time_slot","marker":"TIME_SLOT","instruction":"Show available delivery windows and let customer pick a new time"},{"id":"step_3","type":"confirm","field":"edit","marker":"BOOKING_EDIT","instruction":"Confirm the time change with the customer"}]'::jsonb, true, 1),
  ('b9b4df82-2b89-4a64-b2a3-5e19c0e8d43b', '2f1fab67-4177-4a69-870f-e556ca5219bd', 'change_address', 'Change Booking Address', 'Customer wants to change the delivery address', ARRAY['change address','new address','endre adresse','flytte adresse'], true, '[{"id":"step_1","type":"lookup","field":"booking","marker":"","instruction":"Identify which booking the customer wants to change. Use their verified phone to look up pending bookings."},{"id":"step_2","type":"collect","field":"address","marker":"ADDRESS_SEARCH","instruction":"Ask for the new delivery address and validate service area"},{"id":"step_3","type":"confirm","field":"edit","marker":"BOOKING_EDIT","instruction":"Confirm the address change with the customer"}]'::jsonb, true, 2),
  ('b9b4df82-2b89-4a64-b2a3-5e19c0e8d43b', '2f1fab67-4177-4a69-870f-e556ca5219bd', 'change_car', 'Change Booking Car', 'Customer wants to change the car on a booking', ARRAY['change car','different car','endre bil','bytte bil','wrong car'], true, '[{"id":"step_1","type":"lookup","field":"booking","marker":"","instruction":"Identify which booking the customer wants to change. Use their verified phone to look up pending bookings."},{"id":"step_2","type":"collect","field":"license_plate","marker":"LICENSE_PLATE","instruction":"Ask for the new car registration number"},{"id":"step_3","type":"confirm","field":"edit","marker":"BOOKING_EDIT","instruction":"Confirm the car change with the customer"}]'::jsonb, true, 3),
  ('b9b4df82-2b89-4a64-b2a3-5e19c0e8d43b', '2f1fab67-4177-4a69-870f-e556ca5219bd', 'add_services', 'Add Services to Booking', 'Customer wants to add more services to an existing booking', ARRAY['add service','more services','legge til tjeneste','ekstra service'], true, '[{"id":"step_1","type":"lookup","field":"booking","marker":"","instruction":"Identify which booking the customer wants to modify. Use their verified phone to look up pending bookings."},{"id":"step_2","type":"collect","field":"service","marker":"SERVICE_SELECT","instruction":"Show available additional services and let customer choose"},{"id":"step_3","type":"confirm","field":"edit","marker":"BOOKING_EDIT","instruction":"Confirm the added services with the customer"}]'::jsonb, true, 4),
  ('b9b4df82-2b89-4a64-b2a3-5e19c0e8d43b', '2f1fab67-4177-4a69-870f-e556ca5219bd', 'cancel_booking', 'Cancel Booking', 'Customer wants to cancel a booking', ARRAY['cancel booking','avbestille','kansellere','cancel my order'], true, '[{"id":"step_1","type":"lookup","field":"booking","marker":"","instruction":"Identify which booking the customer wants to cancel. Use their verified phone to look up pending bookings."},{"id":"step_2","type":"confirm","field":"cancellation","marker":"CONFIRM","instruction":"Confirm the cancellation with the customer. Warn that this cannot be undone."}]'::jsonb, true, 5),
  ('b9b4df82-2b89-4a64-b2a3-5e19c0e8d43b', '2f1fab67-4177-4a69-870f-e556ca5219bd', 'view_bookings', 'View My Bookings', 'Customer wants to see their upcoming bookings', ARRAY['my bookings','see bookings','mine bestillinger','vis bestillinger','upcoming orders'], true, '[{"id":"step_1","type":"lookup","field":"customer","marker":"","instruction":"Look up customer by verified phone number"},{"id":"step_2","type":"display","field":"bookings","marker":"","instruction":"Display the customers pending and upcoming bookings"}]'::jsonb, true, 6);
