// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js"
import { brokeredPreviewStorage } from "./previewAuthStorage"
import type { Database } from "./types"

const SUPABASE_URL = "https://qgfaycwsangsqzpveoup.supabase.co"
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFnZmF5Y3dzYW5nc3F6cHZlb3VwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMzIwMDMsImV4cCI6MjA2OTYwODAwM30.Q5dNwdnAxCDwhaEluhFnCO1hbTY4rZ1uhEy284FLhTE"

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Sent on every call so backend proxies can tag Noddi API requests with the
// running Support Hub version (X-Navio-Source-Version).
const APP_VERSION = typeof __APP_COMMIT__ !== "undefined" ? __APP_COMMIT__ : "unknown"

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: { "x-app-version": APP_VERSION },
  },
})
