// AUTO-GENERATED by scripts/generate-edge-functions-manifest.ts — do not edit by hand.
export interface EdgeFunctionInfo {
  name: string;
  description: string;
  /** verify_jwt from supabase/config.toml; null when not configured explicitly. */
  verifyJwt: boolean | null;
  secrets: string[];
  lines: number;
}

export const EDGE_FUNCTIONS: EdgeFunctionInfo[] = [
  {
    "name": "admin-cleanup-users",
    "description": "",
    "verifyJwt": true,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 265
  },
  {
    "name": "admin-create-user",
    "description": "",
    "verifyJwt": true,
    "secrets": [
      "SITE_URL",
      "SUPABASE_ANON_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 342
  },
  {
    "name": "admin-get-all-users",
    "description": "",
    "verifyJwt": true,
    "secrets": [
      "SUPABASE_ANON_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 171
  },
  {
    "name": "admin-update-user-email",
    "description": "",
    "verifyJwt": null,
    "secrets": [
      "SUPABASE_ANON_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 143
  },
  {
    "name": "aircall-sync-contacts",
    "description": "",
    "verifyJwt": false,
    "secrets": [
      "AIRCALL_SYNC_CRON_SECRET",
      "SUPABASE_ANON_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 446
  },
  {
    "name": "aircall-tag-call",
    "description": "",
    "verifyJwt": null,
    "secrets": [
      "SUPABASE_ANON_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 220
  },
  {
    "name": "attach-conversation-to-applicant",
    "description": "",
    "verifyJwt": true,
    "secrets": [
      "SUPABASE_ANON_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 96
  },
  {
    "name": "audit-export",
    "description": "",
    "verifyJwt": null,
    "secrets": [
      "SUPABASE_ANON_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 273
  },
  {
    "name": "auto-close-conversations",
    "description": "",
    "verifyJwt": false,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 196
  },
  {
    "name": "auto-promote-responses",
    "description": "",
    "verifyJwt": true,
    "secrets": [
      "OPENAI_API_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 171
  },
  {
    "name": "backfill-critical-alert-ts",
    "description": "backfill-critical-alert-ts Best-effort backfill of `slack_message_ts` and `slack_channel_id` for recent `critical_alert_sent` notifications. For each notification missing a ts: 1. Resolve the org's Slack bot token + critical channel ID from slack_integrations / inbox_slack_routing. 2. Call conversat",
    "verifyJwt": true,
    "secrets": [
      "SUPABASE_ANON_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 240
  },
  {
    "name": "backfill-sender-fix",
    "description": "",
    "verifyJwt": null,
    "secrets": [
      "SUPABASE_ANON_KEY",
      "SUPABASE_URL"
    ],
    "lines": 247
  },
  {
    "name": "batch-update-embeddings",
    "description": "",
    "verifyJwt": true,
    "secrets": [
      "OPENAI_API_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 121
  },
  {
    "name": "bulk-applicant-action",
    "description": "Bulk applicant action — supports 9 actions on selected applicants. Actions: move_stage, assign, reject, hire, send_email, send_form, add_tags, remove_tags, delete (admin), export_csv.",
    "verifyJwt": true,
    "secrets": [
      "SUPABASE_ANON_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 522
  },
  {
    "name": "bulk-close-old-conversations",
    "description": "",
    "verifyJwt": true,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 109
  },
  {
    "name": "bulk-evaluate-pending-entries",
    "description": "",
    "verifyJwt": true,
    "secrets": [
      "OPENAI_API_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 353
  },
  {
    "name": "bulk-outreach",
    "description": "",
    "verifyJwt": null,
    "secrets": [
      "NODDI_API_BASE",
      "NODDI_API_TOKEN",
      "SUPABASE_ANON_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 827
  },
  {
    "name": "call-events-webhook",
    "description": "",
    "verifyJwt": false,
    "secrets": [
      "AIRCALL_WEBHOOK_TOKEN",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 701
  },
  {
    "name": "classify-agent-edit",
    "description": "",
    "verifyJwt": false,
    "secrets": [
      "OPENAI_API_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 222
  },
  {
    "name": "cleanup-duplicate-messages",
    "description": "",
    "verifyJwt": true,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 183
  },
  {
    "name": "cleanup-email-account-data",
    "description": "",
    "verifyJwt": null,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 119
  },
  {
    "name": "cleanup-expired-form-tokens",
    "description": "Cron-driven: mark expired candidate form tokens and emit audit events. Optionally hard-delete tokens >90 days old.",
    "verifyJwt": false,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 71
  },
  {
    "name": "cleanup-expired-gdpr-exports",
    "description": "Phase 12 M12.2 — Daily sweep of expired GDPR export files. For every gdpr_requests row of type=export whose fulfilled_at is older than the signed-URL TTL (7 days), delete the corresponding object in gdpr-exports bucket and null fulfillment_summary.download_url. The gdpr_requests row itself is preser",
    "verifyJwt": null,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 80
  },
  {
    "name": "cleanup-forwarding-echoes",
    "description": "",
    "verifyJwt": null,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 161
  },
  {
    "name": "create-call-notification",
    "description": "Call notification edge function - handles call event notifications",
    "verifyJwt": null,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 125
  },
  {
    "name": "create-embedding",
    "description": "",
    "verifyJwt": true,
    "secrets": [
      "OPENAI_API_KEY"
    ],
    "lines": 77
  },
  {
    "name": "create-service-ticket",
    "description": "",
    "verifyJwt": true,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 209
  },
  {
    "name": "database-recovery",
    "description": "/ <reference path=\"../_shared/edge-runtime.d.ts\" />",
    "verifyJwt": true,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 281
  },
  {
    "name": "deduplicate-customers",
    "description": "",
    "verifyJwt": true,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 186
  },
  {
    "name": "deploy-widget",
    "description": "",
    "verifyJwt": null,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 1492
  },
  {
    "name": "detach-conversation-from-applicant",
    "description": "",
    "verifyJwt": true,
    "secrets": [
      "SUPABASE_ANON_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 83
  },
  {
    "name": "dev-login",
    "description": "",
    "verifyJwt": null,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 80
  },
  {
    "name": "dispatch-webhook",
    "description": "",
    "verifyJwt": null,
    "secrets": [
      "SUPABASE_URL"
    ],
    "lines": 240
  },
  {
    "name": "download-voicemail",
    "description": "",
    "verifyJwt": true,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 118
  },
  {
    "name": "email-image-proxy",
    "description": "Fetches remote images referenced by email bodies server-side so they render with their original formatting without leaking the agent's IP/cookies to the sender's tracking infrastructure.",
    "verifyJwt": false,
    "secrets": [],
    "lines": 141
  },
  {
    "name": "email-sync-scheduler",
    "description": "",
    "verifyJwt": null,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY"
    ],
    "lines": 105
  },
  {
    "name": "email-webhook",
    "description": "",
    "verifyJwt": null,
    "secrets": [
      "EMAIL_WEBHOOK_SECRET",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 298
  },
  {
    "name": "evaluate-autonomy-levels",
    "description": "",
    "verifyJwt": false,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 276
  },
  {
    "name": "evaluate-conversations",
    "description": "",
    "verifyJwt": false,
    "secrets": [
      "OPENAI_API_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 273
  },
  {
    "name": "extract-customer-memories",
    "description": "",
    "verifyJwt": true,
    "secrets": [
      "OPENAI_API_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 595
  },
  {
    "name": "extract-knowledge-from-history",
    "description": "",
    "verifyJwt": true,
    "secrets": [
      "OPENAI_API_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 319
  },
  {
    "name": "extract-refinement-pattern",
    "description": "",
    "verifyJwt": true,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 119
  },
  {
    "name": "fetch-gmail-attachment",
    "description": "",
    "verifyJwt": null,
    "secrets": [
      "GOOGLE_CLIENT_SECRET",
      "SUPABASE_ANON_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 241
  },
  {
    "name": "fix-sendgrid-webhook",
    "description": "",
    "verifyJwt": true,
    "secrets": [
      "SENDGRID_API_KEY",
      "SENDGRID_INBOUND_TOKEN",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 181
  },
  {
    "name": "fulfill-gdpr-erasure",
    "description": "Phase 12 M12.2 — Fulfill GDPR Article 17 erasure (internal/service-role only). Pipeline: invoke gdpr_erase_applicant RPC (atomic) → delete storage objects           → update request row with summary → audit.",
    "verifyJwt": null,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 115
  },
  {
    "name": "fulfill-gdpr-export",
    "description": "Phase 12 M12.2 — Fulfill GDPR Article 15+20 export (internal/service-role only). Pipeline: collect data → render PDF → download applicant files → build ZIP           → upload to gdpr-exports bucket → sign URL → update request row.",
    "verifyJwt": null,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 199
  },
  {
    "name": "generate-analytics-report",
    "description": "",
    "verifyJwt": true,
    "secrets": [
      "OPENAI_API_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 279
  },
  {
    "name": "generate-candidate-form-token",
    "description": "Recruiter-initiated: create a candidate form token and optionally dispatch via email/SMS. Token creation is delegated to _shared/sendCandidateForm.ts so this path, the bulk path, and the automation path stay on a single code path.",
    "verifyJwt": true,
    "secrets": [
      "SUPABASE_ANON_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 139
  },
  {
    "name": "generate-email-draft",
    "description": "",
    "verifyJwt": true,
    "secrets": [
      "OPENAI_API_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 301
  },
  {
    "name": "get-attachment",
    "description": "",
    "verifyJwt": false,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 429
  },
  {
    "name": "get-candidate-form-fields",
    "description": "Public endpoint: fetch the smart-form field definitions for a validated token.",
    "verifyJwt": false,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 59
  },
  {
    "name": "gmail-oauth",
    "description": "",
    "verifyJwt": null,
    "secrets": [
      "GOOGLE_CLIENT_SECRET",
      "SUPABASE_ANON_KEY",
      "SUPABASE_SERVICE_ROLE_KEY"
    ],
    "lines": 341
  },
  {
    "name": "gmail-sync",
    "description": "",
    "verifyJwt": null,
    "secrets": [
      "GOOGLE_CLIENT_SECRET",
      "SUPABASE_ANON_KEY",
      "SUPABASE_SERVICE_ROLE_KEY"
    ],
    "lines": 806
  },
  {
    "name": "helpscout-import",
    "description": "/ <reference path=\"../_shared/edge-runtime.d.ts\" />",
    "verifyJwt": true,
    "secrets": [
      "HELPSCOUT_APP_ID",
      "HELPSCOUT_APP_SECRET",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 791
  },
  {
    "name": "initiate-gdpr-erasure",
    "description": "Phase 12 M12.2 — Initiate GDPR Article 17 erasure. Recruiter (org admin) endpoint. Requires explicit `confirm: true`. Creates a gdpr_requests row in 'processing' state and dispatches fulfill-gdpr-erasure asynchronously.",
    "verifyJwt": null,
    "secrets": [
      "SUPABASE_ANON_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 140
  },
  {
    "name": "initiate-gdpr-export",
    "description": "Phase 12 M12.2 — Initiate GDPR Article 15+20 export. Recruiter (org admin) endpoint. Creates a gdpr_requests row, fires off fulfill-gdpr-export asynchronously with the service-role key, returns the request_id immediately so the UI can poll.",
    "verifyJwt": null,
    "secrets": [
      "SUPABASE_ANON_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 132
  },
  {
    "name": "manage-import-job",
    "description": "",
    "verifyJwt": null,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 91
  },
  {
    "name": "manual-end-call",
    "description": "",
    "verifyJwt": true,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 145
  },
  {
    "name": "mcp",
    "description": "AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin. To take ownership, delete this banner line; the plugin then leaves the file alone. supabase function: mcp Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js. src/lib/mcp/index.ts",
    "verifyJwt": null,
    "secrets": [],
    "lines": 301
  },
  {
    "name": "meta-data-deletion",
    "description": "meta-data-deletion Public endpoint — Meta calls this when a user requests deletion of their data. Verifies signed_request HMAC, creates a tracking row with a public confirmation code, deletes any stored tokens / oauth user info for that FB user, and returns the status URL Meta requires.",
    "verifyJwt": false,
    "secrets": [
      "META_APP_SECRET",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 108
  },
  {
    "name": "meta-deauthorize",
    "description": "meta-deauthorize Public endpoint — Meta calls this when a user removes our app from their FB account. Verifies signed_request HMAC, marks all integrations created by that FB user as disconnected, and clears stored tokens.",
    "verifyJwt": false,
    "secrets": [
      "META_APP_SECRET",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 59
  },
  {
    "name": "meta-deletion-status",
    "description": "PUBLIC: returns the status of one Meta data-deletion request by its exact confirmation code. No auth required (Meta links users straight here), but the underlying table stays unreadable to anon — lookup is service-role and scoped to a single exact code match.",
    "verifyJwt": false,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 55
  },
  {
    "name": "meta-integration-health-check",
    "description": "Meta Integration Health Check Runs auth/subscription/lead-retrieval probes against Graph API and persists cached result.",
    "verifyJwt": null,
    "secrets": [
      "META_APP_ID",
      "META_APP_SECRET",
      "SUPABASE_ANON_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 313
  },
  {
    "name": "meta-integration-subscribe-webhook",
    "description": "meta-integration-subscribe-webhook Manual-path companion to meta-oauth-finalize. Subscribes a manually-configured integration's page to leadgen webhooks and flips status to 'connected'.",
    "verifyJwt": true,
    "secrets": [
      "SUPABASE_ANON_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 107
  },
  {
    "name": "meta-integration-test-token",
    "description": "Validates a candidate Page Access Token without persisting it.",
    "verifyJwt": null,
    "secrets": [
      "META_APP_ID",
      "META_APP_SECRET",
      "SUPABASE_ANON_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 168
  },
  {
    "name": "meta-lead-webhook",
    "description": "Meta Lead Ads webhook handler — rewritten to use the recruitment_form_field_mappings pipeline (Phase B3).  Always returns HTTP 200 to Meta — failures surfaced via ingestion log.",
    "verifyJwt": false,
    "secrets": [
      "META_APP_SECRET",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 235
  },
  {
    "name": "meta-list-form-fields",
    "description": "Lists Meta Lead Ad form questions for the integration's stored page. Caches results in-memory for 60s to avoid hammering Meta on UI re-renders.",
    "verifyJwt": true,
    "secrets": [
      "SUPABASE_ANON_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 145
  },
  {
    "name": "meta-list-leadgen-forms",
    "description": "meta-list-leadgen-forms Authenticated. Returns lead-gen forms for a configured integration's page, using the server-side page_access_token. The token is never sent to the client. On pages_manage_ads scope error returns { forms: null, scope_missing: true } so the wizard can render a graceful fallback",
    "verifyJwt": true,
    "secrets": [
      "SUPABASE_ANON_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 125
  },
  {
    "name": "meta-oauth-callback",
    "description": "meta-oauth-callback Public endpoint Facebook redirects to. Validates state/nonce, exchanges auth code for a long-lived user token, stashes it on the oauth_states row, then 302s back to the wizard at the origin captured during init.",
    "verifyJwt": false,
    "secrets": [
      "META_APP_ID",
      "META_APP_SECRET",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 137
  },
  {
    "name": "meta-oauth-finalize",
    "description": "meta-oauth-finalize Authenticated. Given a state_id and the operator-selected page_id, derives a page access token from the long-lived user token, subscribes the page to leadgen webhooks, and upserts the integration row.",
    "verifyJwt": true,
    "secrets": [
      "SUPABASE_ANON_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 187
  },
  {
    "name": "meta-oauth-init",
    "description": "meta-oauth-init Authenticated. Generates a CSRF nonce, stores an oauth_states row with the caller's browser origin, returns the Facebook OAuth URL to redirect to.",
    "verifyJwt": true,
    "secrets": [
      "META_APP_ID",
      "SUPABASE_ANON_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 123
  },
  {
    "name": "meta-oauth-list-pages",
    "description": "meta-oauth-list-pages Authenticated. Returns the FB pages the OAuth user manages, using the long-lived user token stashed on the oauth_states row. Page tokens are NOT returned to the client.",
    "verifyJwt": true,
    "secrets": [
      "META_APP_ID",
      "META_APP_SECRET",
      "SUPABASE_ANON_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 135
  },
  {
    "name": "meta-token-exchange-long-lived",
    "description": "Phase B4: Manual long-lived Meta token exchange. Takes a short-lived user token + app secret, exchanges for a long-lived user token, derives a (non-expiring) page token, validates via debug_token, and writes the result to recruitment_meta_integrations.  SECURITY: app_secret and user_token are NEVER ",
    "verifyJwt": true,
    "secrets": [
      "META_APP_ID",
      "META_APP_SECRET",
      "SUPABASE_ANON_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 184
  },
  {
    "name": "meta-token-health-check",
    "description": "Phase B4: Scheduled Meta token health check. Iterates active recruitment_meta_integrations rows, calls debug_token on each page access token, updates status + expiry, and creates admin alerts on degradation transitions. Resolves prior unresolved alerts when status recovers to 'connected'.",
    "verifyJwt": false,
    "secrets": [
      "META_APP_ID",
      "META_APP_SECRET",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 168
  },
  {
    "name": "meta-token-paste-system-user",
    "description": "Phase B4: Save a Meta System User token directly (no exchange). System User tokens never expire and are managed in Business Manager.",
    "verifyJwt": true,
    "secrets": [
      "META_APP_ID",
      "META_APP_SECRET",
      "SUPABASE_ANON_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 127
  },
  {
    "name": "monitor-database-health",
    "description": "",
    "verifyJwt": true,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 120
  },
  {
    "name": "noddi-address-lookup",
    "description": "",
    "verifyJwt": false,
    "secrets": [
      "NODDI_API_BASE",
      "NODDI_API_TOKEN"
    ],
    "lines": 108
  },
  {
    "name": "noddi-booking-proxy",
    "description": "",
    "verifyJwt": false,
    "secrets": [
      "NODDI_API_BASE",
      "NODDI_API_TOKEN"
    ],
    "lines": 432
  },
  {
    "name": "noddi-brands",
    "description": "Proxy for the Noddi backend brand catalog. Returns a slim list of brands (id, name, slug, domain, logo url) used by the support hub to show which brand a live-chat conversation came from. Responses are cached in-memory for a few minutes to avoid hammering the API.",
    "verifyJwt": true,
    "secrets": [
      "NODDI_API_BASE",
      "NODDI_API_TOKEN"
    ],
    "lines": 149
  },
  {
    "name": "noddi-customer-lookup",
    "description": "",
    "verifyJwt": null,
    "secrets": [
      "LOG_NODDI_DEBUG",
      "NODDI_API_BASE",
      "NODDI_API_TOKEN",
      "NODDI_CACHE_TTL_SECONDS",
      "PARTNER_BASE_URL",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 1840
  },
  {
    "name": "noddi-search-by-name",
    "description": "",
    "verifyJwt": true,
    "secrets": [
      "NODDI_API_BASE",
      "NODDI_API_TOKEN",
      "SUPABASE_ANON_KEY",
      "SUPABASE_URL"
    ],
    "lines": 163
  },
  {
    "name": "noddi-tickets",
    "description": "Proxy for the Noddi backend ticket API. The Support Hub NEVER stores tickets locally — every read/write goes to Noddi.",
    "verifyJwt": true,
    "secrets": [
      "NODDI_API_BASE",
      "NODDI_API_TOKEN"
    ],
    "lines": 317
  },
  {
    "name": "oversikt-metrics",
    "description": "Recruitment Oversikt — aggregated metrics endpoint. POST { organization_id, position_id?, time_window: '7d'|'30d'|'90d'|'all',        assignment_scope: 'mine'|'unassigned'|'all', user_id? }",
    "verifyJwt": true,
    "secrets": [
      "SUPABASE_ANON_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 302
  },
  {
    "name": "process-automation-queue",
    "description": "",
    "verifyJwt": null,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 477
  },
  {
    "name": "process-file-extraction-queue",
    "description": "",
    "verifyJwt": false,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 87
  },
  {
    "name": "process-mention-notifications",
    "description": "",
    "verifyJwt": true,
    "secrets": [
      "APP_URL",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 461
  },
  {
    "name": "process-scheduled-emails",
    "description": "",
    "verifyJwt": false,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 185
  },
  {
    "name": "process-scheduled-sms",
    "description": "Cron-invoked: process due rows in recruitment_scheduled_sms.",
    "verifyJwt": false,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 135
  },
  {
    "name": "process-scoring-queue",
    "description": "",
    "verifyJwt": false,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 351
  },
  {
    "name": "promote-response",
    "description": "",
    "verifyJwt": true,
    "secrets": [
      "OPENAI_API_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 127
  },
  {
    "name": "recruitment-backfill-form-field-keys",
    "description": "One-time backfill: populate recruitment_form_field_mappings.meta_question_key for rows where it is NULL by re-fetching questions from Meta.  Idempotent: only updates rows where meta_question_key IS NULL. Re-running on already-backfilled data is a no-op.  Matching strategy per row:   1. Try q.id === ",
    "verifyJwt": null,
    "secrets": [
      "SUPABASE_ANON_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 321
  },
  {
    "name": "recruitment-bulk-import-execute",
    "description": "Bulk import — EXECUTE. Synchronously paginates Meta /leads per form_mapping in scope and ingests each lead.",
    "verifyJwt": true,
    "secrets": [
      "SUPABASE_ANON_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 220
  },
  {
    "name": "recruitment-bulk-import-start",
    "description": "Bulk import — DRY RUN. Creates a pending recruitment_bulk_imports row, paginates Meta /leads per form just to count, and reports per-form mapping completeness.",
    "verifyJwt": true,
    "secrets": [
      "SUPABASE_ANON_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 174
  },
  {
    "name": "recruitment-bulk-import-status",
    "description": "Bulk import — STATUS poll endpoint.",
    "verifyJwt": true,
    "secrets": [
      "SUPABASE_ANON_KEY",
      "SUPABASE_URL"
    ],
    "lines": 58
  },
  {
    "name": "recruitment-quarantine-approve",
    "description": "Quarantine approve — sets import_status='approved' for given applicants (org-scoped, admin-only).",
    "verifyJwt": true,
    "secrets": [
      "SUPABASE_ANON_KEY",
      "SUPABASE_URL"
    ],
    "lines": 58
  },
  {
    "name": "refine-suggestion",
    "description": "",
    "verifyJwt": true,
    "secrets": [
      "OPENAI_API_KEY"
    ],
    "lines": 127
  },
  {
    "name": "resend-user-invite",
    "description": "",
    "verifyJwt": true,
    "secrets": [
      "SITE_URL",
      "SUPABASE_ANON_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 193
  },
  {
    "name": "review-open-critical",
    "description": "",
    "verifyJwt": null,
    "secrets": [
      "APP_URL",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 312
  },
  {
    "name": "review-queue",
    "description": "",
    "verifyJwt": true,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 160
  },
  {
    "name": "revoke-candidate-form-token",
    "description": "Recruiter-initiated: revoke an active candidate form token.",
    "verifyJwt": true,
    "secrets": [
      "SUPABASE_ANON_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 83
  },
  {
    "name": "sanitize-knowledge-entries",
    "description": "",
    "verifyJwt": true,
    "secrets": [
      "OPENAI_API_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 222
  },
  {
    "name": "score-application",
    "description": "",
    "verifyJwt": true,
    "secrets": [
      "SUPABASE_ANON_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 128
  },
  {
    "name": "search-customers-by-name",
    "description": "",
    "verifyJwt": null,
    "secrets": [
      "SUPABASE_ANON_KEY",
      "SUPABASE_URL"
    ],
    "lines": 81
  },
  {
    "name": "search-knowledge",
    "description": "",
    "verifyJwt": true,
    "secrets": [
      "OPENAI_API_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 105
  },
  {
    "name": "send-chat-transcript",
    "description": "",
    "verifyJwt": null,
    "secrets": [
      "RESEND_API_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 259
  },
  {
    "name": "send-email",
    "description": "",
    "verifyJwt": null,
    "secrets": [
      "SENDGRID_API_KEY"
    ],
    "lines": 104
  },
  {
    "name": "send-organization-invite",
    "description": "",
    "verifyJwt": null,
    "secrets": [
      "SENDGRID_API_KEY",
      "SUPABASE_ANON_KEY",
      "SUPABASE_URL"
    ],
    "lines": 355
  },
  {
    "name": "send-recruitment-email",
    "description": "",
    "verifyJwt": true,
    "secrets": [
      "PUBLIC_APP_URL",
      "SUPABASE_ANON_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 347
  },
  {
    "name": "send-recruitment-sms",
    "description": "",
    "verifyJwt": true,
    "secrets": [
      "PUBLIC_APP_URL",
      "SUPABASE_ANON_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 266
  },
  {
    "name": "send-reply-email",
    "description": "",
    "verifyJwt": null,
    "secrets": [
      "SENDGRID_API_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 634
  },
  {
    "name": "send-slack-notification",
    "description": "",
    "verifyJwt": false,
    "secrets": [
      "APP_URL",
      "OPENAI_API_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 754
  },
  {
    "name": "send-test-critical-alert",
    "description": "send-test-critical-alert Admin-only utility that fires a real critical Slack alert using a special sentinel keyword (\"test-trigger-please-ignore\") so admins can verify the 👍 / 👎 / 🔇 reaction → feedback loop end-to-end without waiting for a real customer issue. Always returns HTTP 200 with `{ ok, ",
    "verifyJwt": true,
    "secrets": [
      "SUPABASE_ANON_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 218
  },
  {
    "name": "send-ticket-notification",
    "description": "",
    "verifyJwt": true,
    "secrets": [
      "SUPABASE_ANON_KEY",
      "SUPABASE_URL"
    ],
    "lines": 191
  },
  {
    "name": "sendgrid-inbound",
    "description": "",
    "verifyJwt": false,
    "secrets": [
      "SENDGRID_API_KEY",
      "SENDGRID_INBOUND_TOKEN",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 707
  },
  {
    "name": "sendgrid-setup",
    "description": "",
    "verifyJwt": null,
    "secrets": [
      "SENDGRID_API_KEY",
      "SENDGRID_INBOUND_TOKEN",
      "SUPABASE_ANON_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 230
  },
  {
    "name": "sla-breach-notifier",
    "description": "",
    "verifyJwt": false,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 293
  },
  {
    "name": "slack-daily-digest",
    "description": "",
    "verifyJwt": false,
    "secrets": [
      "OPENAI_API_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 435
  },
  {
    "name": "slack-event-handler",
    "description": "slack-event-handler Public Slack Events API endpoint. Listens for `reaction_added` on bot messages (critical alerts) and writes feedback rows. Reactions tracked: 👍 (+1)        → mark trigger as useful 👎 (-1)        → mark trigger as false alarm 🔇 (mute)      → mute the matched keyword for 7 days ",
    "verifyJwt": false,
    "secrets": [
      "SLACK_SIGNING_SECRET",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 236
  },
  {
    "name": "slack-integration",
    "description": "",
    "verifyJwt": null,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 310
  },
  {
    "name": "slack-list-channels",
    "description": "",
    "verifyJwt": true,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 141
  },
  {
    "name": "slack-list-subteams",
    "description": "Lists Slack User Groups (subteams) for the calling org's connected Slack workspace. Used by the critical-alert routing UI so admins can pick a subteam to ping instead of @channel. Body: { organization_id: string, use_secondary?: boolean } Returns: { subteams: Array<{ id, handle, name, description, u",
    "verifyJwt": true,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 89
  },
  {
    "name": "slack-list-users",
    "description": "Lists Slack workspace members (humans only, deduped) for the calling org's connected Slack workspace. Used by the critical-alert routing UI so admins can pick a single triage owner to ping. Body: { organization_id: string, use_secondary?: boolean } Returns: { users: Array<{ id, name, real_name, disp",
    "verifyJwt": true,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 96
  },
  {
    "name": "sms-inbound",
    "description": "Public webhook: receives inbound SMS from any provider. Path-routed: /functions/v1/sms-inbound/<provider>",
    "verifyJwt": false,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 159
  },
  {
    "name": "sms-status-callback",
    "description": "Public webhook: receives delivery status updates from any SMS provider. Path-routed: /functions/v1/sms-status-callback/<provider>",
    "verifyJwt": false,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 83
  },
  {
    "name": "snooze-notifier",
    "description": "",
    "verifyJwt": false,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 69
  },
  {
    "name": "submit-candidate-form",
    "description": "Public endpoint: submit the candidate form. Writes field values + builtin columns, marks the token used, and lets existing DB triggers enqueue re-scoring.",
    "verifyJwt": false,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 126
  },
  {
    "name": "submit-feedback",
    "description": "",
    "verifyJwt": true,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 97
  },
  {
    "name": "suggest-replies",
    "description": "",
    "verifyJwt": true,
    "secrets": [
      "OPENAI_API_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 318
  },
  {
    "name": "sync-auth-templates",
    "description": "",
    "verifyJwt": null,
    "secrets": [
      "SUPABASEACCESS_TOKEN",
      "SUPABASEPROJECT_REF",
      "SUPABASE_ANON_KEY",
      "SUPABASE_URL"
    ],
    "lines": 156
  },
  {
    "name": "sync-unlinked-calls",
    "description": "",
    "verifyJwt": true,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 281
  },
  {
    "name": "test-aircall-credentials",
    "description": "",
    "verifyJwt": true,
    "secrets": [],
    "lines": 103
  },
  {
    "name": "test-download-voicemail",
    "description": "",
    "verifyJwt": null,
    "secrets": [],
    "lines": 41
  },
  {
    "name": "timezone-aware-scheduler",
    "description": "",
    "verifyJwt": false,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 176
  },
  {
    "name": "track-outcome",
    "description": "",
    "verifyJwt": true,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 146
  },
  {
    "name": "translate-text",
    "description": "",
    "verifyJwt": true,
    "secrets": [
      "OPENAI_API_KEY"
    ],
    "lines": 146
  },
  {
    "name": "triage-pattern-mining",
    "description": "triage-pattern-mining Weekly scan that turns historical conversations + Slack feedback into concrete tuning proposals (add/remove keyword, raise threshold). Pulls last 60 days of feedback, identifies: - Keywords with ≥3 alerts and ≥60% 👎 rate → propose remove_keyword - AI categories with ≥3 alerts ",
    "verifyJwt": false,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 197
  },
  {
    "name": "trigger-gmail-sync",
    "description": "",
    "verifyJwt": null,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY"
    ],
    "lines": 60
  },
  {
    "name": "update-customer-alternative-email",
    "description": "",
    "verifyJwt": null,
    "secrets": [
      "SUPABASE_ANON_KEY",
      "SUPABASE_URL"
    ],
    "lines": 107
  },
  {
    "name": "update-sendgrid-token",
    "description": "",
    "verifyJwt": true,
    "secrets": [
      "SENDGRID_INBOUND_TOKEN",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 172
  },
  {
    "name": "update-service-ticket",
    "description": "",
    "verifyJwt": null,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 183
  },
  {
    "name": "update-ticket-status",
    "description": "",
    "verifyJwt": true,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 217
  },
  {
    "name": "validate-candidate-form-token",
    "description": "Public endpoint: validate a candidate form token + identity check.",
    "verifyJwt": false,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 61
  },
  {
    "name": "validate-stage-progression",
    "description": "",
    "verifyJwt": true,
    "secrets": [
      "SUPABASE_ANON_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 168
  },
  {
    "name": "widget-ai-chat",
    "description": "",
    "verifyJwt": false,
    "secrets": [
      "OPENAI_API_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 1470
  },
  {
    "name": "widget-ai-feedback",
    "description": "",
    "verifyJwt": false,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 162
  },
  {
    "name": "widget-chat",
    "description": "",
    "verifyJwt": false,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 1034
  },
  {
    "name": "widget-config",
    "description": "",
    "verifyJwt": false,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 120
  },
  {
    "name": "widget-search-faq",
    "description": "",
    "verifyJwt": false,
    "secrets": [
      "OPENAI_API_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 185
  },
  {
    "name": "widget-send-verification",
    "description": "",
    "verifyJwt": false,
    "secrets": [
      "MCP_URL",
      "NODDI_API_BASE",
      "NODDI_API_TOKEN",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 198
  },
  {
    "name": "widget-submit",
    "description": "",
    "verifyJwt": false,
    "secrets": [
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 284
  },
  {
    "name": "widget-verify-phone",
    "description": "",
    "verifyJwt": false,
    "secrets": [
      "MCP_URL",
      "NODDI_API_BASE",
      "NODDI_API_TOKEN",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 222
  },
  {
    "name": "wipe-organization-data",
    "description": "",
    "verifyJwt": null,
    "secrets": [
      "SUPABASE_ANON_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL"
    ],
    "lines": 363
  }
];

export const EDGE_FUNCTIONS_GENERATED_AT = "2026-09-01T17:32:07.855Z";
