name: UI Guardrails

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  ui-guards:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tabs/buttons overflow linting
      run: npx tsx scripts/lint-tabs-overflow.ts
      
    - name: Run long labels tab tests
      run: npx vitest --run --reporter=verbose -t "long-labels"
      
    - name: Report success
      run: echo "✅ All UI guardrails passed!"